/* 会话屏样式:与 TaskListScreen 共用 theme token;拆成独立文件是为控制单文件行数。 */
import { StyleSheet } from "react-native";

import { theme } from "../theme";

export const sessionStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.border,
  },
  backButton: { paddingVertical: 4, paddingRight: 4 },
  backText: { color: theme.info, fontSize: 14 },
  headerBody: { flex: 1, gap: 2 },
  title: { color: theme.primary, fontSize: 16, fontWeight: "600" },
  statusText: { color: theme.foregroundSubtle, fontSize: 11 },
  statusError: { color: theme.destructive },
  retryButton: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  retryText: { color: theme.foreground, fontSize: 12 },
  listContent: { paddingVertical: 12, paddingHorizontal: 14, gap: 10 },
  row: { gap: 4 },
  userRow: {
    alignSelf: "flex-end",
    maxWidth: "86%",
    backgroundColor: theme.card,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  userLabel: { color: theme.foregroundSubtle, fontSize: 10 },
  userText: { color: theme.foreground, fontSize: 14, lineHeight: 20 },
  attachmentText: { color: theme.foregroundSubtle, fontSize: 11, lineHeight: 16 },
  assistantText: { color: theme.foreground, fontSize: 14, lineHeight: 21 },
  cursor: { color: theme.info, fontSize: 14 },
  rowHint: { color: theme.foregroundSubtle, fontSize: 11 },
  reasoningText: { color: theme.foregroundSubtle, fontSize: 12, lineHeight: 18, fontStyle: "italic" },
  toolCard: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.border,
    borderRadius: 10,
    backgroundColor: theme.panel,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  toolHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  toolName: { color: theme.foreground, fontSize: 12, fontWeight: "600", flexShrink: 1 },
  toolStatus: { fontSize: 11, marginLeft: "auto" },
  toolOutput: { color: theme.foregroundSubtle, fontSize: 11, lineHeight: 16 },
  toolError: { color: theme.destructive, fontSize: 11, lineHeight: 16 },
  turnDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.border,
    paddingTop: 8,
    marginTop: 4,
  },
  turnText: { color: theme.foregroundSubtle, fontSize: 10 },
  stopButton: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.destructive,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  stopText: { color: theme.destructive, fontSize: 12, fontWeight: "600" },
  listHeader: { gap: 8 },
  /** 过程折叠块:一行摘要 + 展开后的过程行。 */
  processBlock: { gap: 6 },
  processHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.border,
    backgroundColor: theme.panel,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  processLabel: { color: theme.foregroundSubtle, fontSize: 12 },
  processChevron: { color: theme.info, fontSize: 11 },
  processBody: {
    gap: 8,
    paddingLeft: 8,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: theme.border,
  },
  loadOlder: { alignItems: "center", paddingVertical: 10 },
  loadOlderText: { color: theme.foregroundSubtle, fontSize: 11, textAlign: "center", paddingVertical: 8 },
  emptyText: { color: theme.foregroundSubtle, fontSize: 13, textAlign: "center", paddingTop: 40 },
  sendError: { color: theme.destructive, fontSize: 12, paddingHorizontal: 16, paddingBottom: 4 },
});
